[package]
name = "tide"
version = "0.1.0"
edition = "2024"

[dependencies]
tide = "0.14.0"
async-std = { version = "1.10", features = ["attributes"] }
serde = { version = "1.0.219", features = ["derive"] }
